# **PYTHON CODING INTERVIEW 50 QUESTIONS SOLUTIONS**


**CODED BY: ABHIJEET SARKAR (M.TECH GEOINFORMATICS)**





In [ ]:
#1. Write a Python program to get the largest number from a list.
def get_largest_number(numbers):
    return max(numbers)

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(get_largest_number(numbers))

10


In [1]:
 #2. a) Write a Python script to concatenate two dictionaries to create a new one. b) Write a Python program to sort a dictionary by key. 


#a) Write a Python script to concatenate two dictionaries to create a new one
dict1 = {1: "Apple", 2: "Banana"}
dict2 = {3: "Carrot", 4: "Date"}

# Using the `update()` method
dict1.update(dict2)
print(dict1)

# Using the `**` operator
dict1 = {1: "Apple", 2: "Banana"}
dict3 = {**dict1, **dict2}
print(dict3)


#b) Write a Python program to sort a dictionary by key. 
my_dict = {3: "Three", 4: "Four", 2: "Two", 1: "One"}
sorted_dict = dict(sorted(my_dict.items()))
print(sorted_dict)



{1: 'Apple', 2: 'Banana', 3: 'Carrot', 4: 'Date'}
{1: 'Apple', 2: 'Banana', 3: 'Carrot', 4: 'Date'}
{1: 'One', 2: 'Two', 3: 'Three', 4: 'Four'}


In [ ]:
# 3. a) Write a Python program to create a tuple with different data types. b) Write a Python program to find the repeated items of a tuple.
# Create a tuple with different data types
my_tuple = (1, "Hello", 3.14, ["a", "b"])

print(my_tuple)

(1, 'Hello', 3.14, ['a', 'b'])


In [ ]:
# b) Write a Python program to find the repeated items of a tuple.
my_tuple = (1, 2, 2, 3, 4, 5, 3, 6)

# Find the repeated items of a tuple
repeated_items = [item for item in my_tuple if my_tuple.count(item) > 1]

print(set(repeated_items))


{2, 3}


In [ ]:
#  4. Write a Python program that accepts a word from the user and reverse it.
# Get input word from the user
word = input("Enter a word: ")

# Reverse the word
reverse_word = word[::-1]

print("The reversed word is:", reverse_word)


Enter a word: abhijeet
The reversed word is: teejihba


In [ ]:
#  5. Write a phython program to demonstrate functions. 
def add(a, b):
    """
   This function takes two numbers and returns their sum
    """
    return a + b

def multiply(a, b):
    """
    This function takes two numbers and returns their product
    """
    return a * b

# Function calls
num1 = 5
num2 = 10
print("Sum:", add(num1, num2))
print("Product:", multiply(num1, num2))


Sum: 15
Product: 50


In [ ]:
#6. Write a phython program to demonstrate classes. 
class Dog:
    """
    This is a class representing a dog
    """
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        """
        This method makes the dog bark
        """
        print(f"{self.name} says bheu bheu!")

    def show_breed(self):
        """
        Show the breed of the dog
        """
        print(f'{self.name}\'s breed is {self.breed}')
      
# Create an instance of the Dog class
dog = Dog("Tomy", "Golden Retriever")
dog.bark()
dog.show_breed()

Tomy says bheu bheu!
Tomy's breed is Golden Retriever


In [ ]:
#7. Write a program to perform file operations. 
# Open a file for writing
file = open("example.txt", "w")

# Write to the file
file.write("This is an example abhijeet assignment file.")

# Close the file
file.close()

# Open the file for reading
file = open("example.txt", "r")

# Read the contents of the file
print(file.read())

# Close the file
file.close()

# Delete the file
import os
os.remove("example.txt")


This is an example abhijeet assignment file.


In [ ]:
#8. Write a Python program to check that a string contains only a certain set of characters (in this case a-z, A-Z and 0-9).
import re

def check_string(string):
    pattern = '^[a-zA-Z0-9]+$'
    if re.search(pattern, string):
        return True
    else:
        return False

print(check_string("Hello123")) # True
print(check_string("Hello&_%23")) # False


True
False


In [ ]:
#9. Write a Python program to interchange first and last elements in a list
def interchange_first_last(lst):
    lst[0], lst[-1] = lst[-1], lst[0]
    return lst

example_list = [1, 2, 3, 4, 5]
print(interchange_first_last(example_list)) # [5, 2, 3, 4, 1]


[5, 2, 3, 4, 1]


In [ ]:
#10. Write a Python program to swap two elements in a list
def swap_elements(lst, index1, index2):
    lst[index1], lst[index2] = lst[index2], lst[index1]
    return lst

example_list = [1, 2, 3, 4, 5]
print(swap_elements(example_list, 1, 3)) # [1, 4, 3, 2, 5]


[1, 4, 3, 2, 5]


In [ ]:
#11. Write a Python to find length of list
def find_length_of_list(lst):
    return len(lst)

# Example usage
my_list = [1, 2, 3, 4, 5]
print(find_length_of_list(my_list))


5


In [ ]:
#12. Write a Python to check if element exists in list Different ways to clear a list in Python
# Method 1: Using the clear() function
my_list = [1, 2, 3, 4, 5]
my_list.clear()
print(my_list) # Output: []

# Method 2: Reassigning the variable to an empty list
my_list = [1, 2, 3, 4, 5]
my_list = []
print(my_list) # Output: []

# Method 3: Using slicing to remove all elements
my_list = [1, 2, 3, 4, 5]
del my_list[:]
print(my_list) # Output: []


[]
[]
[]


In [ ]:
#13. Write a Python Reversing a List.
#Using the reverse() function
my_list = [1, 2, 3, 4, 5]
my_list.reverse()
print(my_list) # Output: [5, 4, 3, 2, 1]

#Using slicing with a negative step
my_list = [1, 2, 3, 4, 5]
print(my_list[::-1]) # Output: [5, 4, 3, 2, 1]


[5, 4, 3, 2, 1]
[5, 4, 3, 2, 1]


In [ ]:
#14. Write a Python program to find sum of elements in list.
def sum_list(lst):
    return sum(lst)

print(sum_list([1, 2, 3, 4, 5]))


15


In [ ]:
#15. Write a Python  program  Multiply all numbers in the list.
def multiply_list(lst):
    result = 1
    for i in lst:
        result *= i
    return result

print(multiply_list([1, 2, 3, 4, 5]))

120


In [ ]:
#16. Write a Python program to find smallest number in a list.
def find_smallest(lst):
    return min(lst)

print(find_smallest([3,2,1,5,7,8,9]))


1


In [ ]:
#17. Write  Python program to find largest number in a list.
def find_largest(lst):
    return max(lst)

print(find_largest([3,2,1,5,7,8,9]))


9


In [ ]:
#18. Write a Python program to find second largest number in a list.
def find_second_largest(lst):
    lst.sort(reverse=True)
    return lst[1]

print(find_second_largest([3,2,1,5,7,8,9]))


8


In [ ]:
#19. Write a  Python program to find N largest elements from a list.
def find_n_largest(lst, n):
    lst.sort(reverse=True)
    return lst[:n]

print(find_n_largest([3,2,1,5,7,8,9],3))


[9, 8, 7]


In [ ]:
#20. Write a Python program to print even numbers in a list.
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for number in numbers:
    if number % 2 == 0:
        print(number)


2
4
6
8
10


In [ ]:
#21. Write a Python program to print odd numbers in a List.
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for number in numbers:
    if number % 2 != 0:
        print(number)


1
3
5
7
9


In [ ]:
#22. Write a Python program to print all even numbers in a range.
def print_even_numbers(start, end):
    for i in range(start, end + 1):
        if i % 2 == 0:
            print(i)

print_even_numbers(1, 10)


2
4
6
8
10


In [ ]:
#23. Python program to add two Matrices.

def add_matrices(mat1, mat2):
    # Check if the matrices have the same dimensions
    if len(mat1) != len(mat2) or len(mat1[0]) != len(mat2[0]):
        raise ValueError("Error: Matrices have different dimensions")

    # Create a new matrix with the same dimensions as mat1 and mat2
    result = [[0 for j in range(len(mat1[0]))] for i in range(len(mat1))]

    # Iterate through the rows and columns of the matrices
    for i in range(len(mat1)):
        for j in range(len(mat1[0])):
            result[i][j] = mat1[i][j] + mat2[i][j]

    return result

# Example usage:
mat1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mat2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
result = add_matrices(mat1, mat2)
print(result)


[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [ ]:
#24.Python program to multiply two matrices.

def multiply_matrices(mat1, mat2):
    # Check if the matrices can be multiplied
    if len(mat1[0]) != len(mat2):
        raise ValueError("Error: The number of columns of the first matrix must be equal to the number of rows of the second matrix")

    # Create a new matrix with dimensions len(mat1) x len(mat2[0])
    result = [[0 for j in range(len(mat2[0]))] for i in range(len(mat1))]

    # Iterate through the rows of the first matrix
    for i in range(len(mat1)):
        # Iterate through the columns of the second matrix
        for j in range(len(mat2[0])):
            # Iterate through the rows of the second matrix
            for k in range(len(mat2)):
                result[i][j] += mat1[i][k] * mat2[k][j]

    return result

# Example usage:
mat1 = [[1, 2, 3], [4, 5, 6]]
mat2 = [[7, 8], [9, 10], [11, 12]]
result = multiply_matrices(mat1, mat2)
print(result)


[[58, 64], [139, 154]]


In [ ]:
#25.Python program for Matrix Product.

def matrix_product(A, B):
    # Get the dimensions of the matrices
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])
    
    # Make sure the matrices can be multiplied
    if cols_A != rows_B:
        raise ValueError("The number of columns in A must match the number of rows in B.")
        
    # Create a result matrix filled with zeros
    result = [[0 for row in range(cols_B)] for col in range(rows_A)]
    
    # Perform the matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]
                
    return result
# Example usage
A = [[1, 2, 3], [4, 5, 6]]
B = [[7, 8], [9, 10], [11, 12]]
print(matrix_product(A, B))


[[58, 64], [139, 154]]


In [ ]:
#26.Adding and Subtracting Matrices in Python.

import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.add(matrix1, matrix2)
print(result)


[[ 6  8]
 [10 12]]


In [ ]:
#27.Transpose a matrix in Single line in Python.
import numpy as np

matrix = np.array([[1, 2], [3, 4]])

result = np.transpose(matrix)
print(result)


[[1 3]
 [2 4]]


In [ ]:
#28.Python Matrix creation of n*n.

import numpy as np

n = 3
matrix = np.full((n, n), 7)
print(matrix)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#28.Python Matrix creation of n*n.

import numpy as np

n = 3
matrix = np.identity(n)
print(matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#28.Python Matrix creation of n*n.

import numpy as np

n = 3
matrix = np.ones((n, n))
print(matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#28.Python Matrix creation of n*n.

import numpy as np

n = 3
matrix = np.zeros((n, n))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#28.Python Matrix creation of n*n.

import numpy as np

n = 3
matrix = np.random.rand(n, n)
print(matrix)

[[0.50532107 0.68791124 0.89544769]
 [0.39067573 0.69583632 0.86133953]
 [0.21921863 0.50288493 0.09945333]]


In [ ]:
#29.Python Get Kth Column of Matrix.

import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

column = matrix[:, 1]
print(column)


[2 5 8]


In [ ]:
#30.Python – Vertical Concatenation in Matrix.
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

column = matrix[:,1]
print(column)


[2 5 8]


In [ ]:
#30.Python – Vertical Concatenation in Matrix.
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
k = 1
column = np.take(matrix, k, axis=1)
print(column)


[2 5 8]


In [ ]:
#30.Python – Vertical Concatenation in Matrix.
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.vstack((a, b))
print(c)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#31. Python Program to print the pattern ‘G’.
pattern = ""
for row in range(0,7):
    for col in range(0,7):
        if ((col == 1 and row != 0 and row != 6) or ((row == 0 or row == 6) and col > 1 and col < 5) or
            (row == 3 and col > 2 and col < 6) or (col == 5 and row != 0 and row != 2 and row != 6)):
            pattern = pattern + "#"
        else:
            pattern = pattern + " "
    pattern = pattern + "\n"
print(pattern)

  ###  
 #   # 
 #     
 # ### 
 #   # 
 #   # 
  ###  



In [ ]:
#32.Python Program to print an Inverted Star Pattern.
for i in range(5, 0, -1):
    print("*" * i)


*****
****
***
**
*


In [ ]:
#33.Python Program to print double sided stair-case pattern.
for i in range(1, 6):
    print(" " * (5 - i) + "*" * i + "*" * (i - 1))

for i in range(4, 0, -1):
    print(" " * (5 - i) + "*" * i + "*" * (i - 1))


    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


In [ ]:
#34.Python Program to print with your own font.
import pyfiglet

text = "Abhijeet Sarkar"
custom_font = pyfiglet.figlet_format(text, font='big')
print(custom_font)


          _     _     _ _           _      _____            _              
    /\   | |   | |   (_|_)         | |    / ____|          | |             
   /  \  | |__ | |__  _ _  ___  ___| |_  | (___   __ _ _ __| | ____ _ _ __ 
  / /\ \ | '_ \| '_ \| | |/ _ \/ _ \ __|  \___ \ / _` | '__| |/ / _` | '__|
 / ____ \| |_) | | | | | |  __/  __/ |_   ____) | (_| | |  |   < (_| | |   
/_/    \_\_.__/|_| |_|_| |\___|\___|\__| |_____/ \__,_|_|  |_|\_\__,_|_|   
                      _/ |                                                 
                     |__/                                                  



In [ ]:
#35. Python program to get Current Time

from datetime import datetime

current_time = datetime.now().time()
time_string = current_time.strftime("%H:%M:%S")
print("Current Time is:", time_string)



Current Time is: 14:27:17


In [ ]:
#37.Get Current Date and Time using Python
from datetime import datetime

current_datetime = datetime.now()
datetime_string = current_datetime.strftime("%Y-%m-%d %H:%M:%S")
print("Current Date and Time is:", datetime_string)


Current Date and Time is: 2023-01-20 14:28:31


In [ ]:
#38.Python Find yesterday’s, today’s and tomorrow’s date
from datetime import datetime, timedelta

yesterday = datetime.now() - timedelta(days=1)
print("Yesterday's date:", yesterday.date())

today = datetime.now()
print("Today's date:", today.date())

tomorrow = datetime.now() + timedelta(days=1)
print("Tomorrow's date:", tomorrow.date())


Yesterday's date: 2023-01-19
Today's date: 2023-01-20
Tomorrow's date: 2023-01-21


In [ ]:
#39.Python program to convert time from 12 hour to 24 hour format
from datetime import datetime

time_12h = "12:45 PM"
time_24h = datetime.strptime(time_12h, "%I:%M %p").strftime("%H:%M")
print("12-hour format:", time_12h)
print("24-hour format:", time_24h)


12-hour format: 12:45 PM
24-hour format: 12:45


In [ ]:
#40.Python program to find difference between current time and given time

from datetime import datetime, timedelta

given_time = "20:30:00"
current_time = datetime.now().time()

time_diff = datetime.combine(datetime.today(), current_time) - datetime.combine(datetime.today(), datetime.strptime(given_time, "%H:%M:%S").time())

print("Current Time:", current_time)
print("Given Time: ", given_time)
print("Difference: ", time_diff)


Current Time: 14:32:16.936393
Given Time:  20:30:00
Difference:  -1 day, 18:02:16.936393


In [ ]:
#41.Python Program to Create a Lap Timer
import time

lap_times = []

print("Starting Timer...")
start_time = time.time()

while True:
    lap_time = time.time() - start_time
    lap_times.append(lap_time)

    print(f"Lap {len(lap_times)}: {lap_time:.2f} seconds")
    input("Press Enter to take the next lap...")


In [ ]:
#42.Convert date string to timestamp in Python
from datetime import datetime

date_string = "2023-01-20"
date_object = datetime.strptime(date_string, "%Y-%m-%d")
timestamp = int(date_object.timestamp())
print("Date String:", date_string)
print("Timestamp:", timestamp)


Date String: 2023-01-20
Timestamp: 1674172800


In [ ]:
#43.How to convert timestamp string to datetime object in Python?
from datetime import datetime

timestamp_string = "1674172800"
timestamp = int(timestamp_string)
date_object = datetime.fromtimestamp(timestamp)
print("Timestamp String:", timestamp_string)
print("Datetime object:", date_object)


Timestamp String: 1674172800
Datetime object: 2023-01-20 00:00:00


In [ ]:
#44.Find number of times every day occurs in a Year.
import datetime
import calendar

def day_occur_time(year):
	
	# stores days in a week
	days = [ "Monday", "Tuesday", "Wednesday",
		"Thursday", "Friday", "Saturday",
		"Sunday" ]
	
	# Initialize all counts as 52
	L = [52 for i in range(7)]
	
	# Find the index of the first day
	# of the year
	pos = -1
	day = datetime.datetime(year, month = 1, day = 1).strftime("%A")
	for i in range(7):
		if day == days[i]:
			pos = i
			
	# mark the occurrence to be 53 of 1st day
	# and 2nd day if the year is leap year
	if calendar.isleap(year):
		L[pos] += 1
		L[(pos+1)%7] += 1
		
	else:
		L[pos] += 1
		
	
	# Print the days
	for i in range(7):
		print(days[i], L[i])
	

# Driver Code
year = 2023
day_occur_time(year)


Monday 52
Tuesday 52
Wednesday 52
Thursday 52
Friday 52
Saturday 52
Sunday 53


In [ ]:
#45.Python Program to Reverse a linked list
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, data):
        new_node = Node(data)
        if not self.head:
            self.head = new_node
            return
        current = self.head
        while current.next:
            current = current.next
        current.next = new_node

    def reverse(self):
        prev = None
        current = self.head
        while current:
            next_node = current.next
            current.next = prev
            prev = current
            current = next_node
        self.head = prev

    def print_list(self):
        current = self.head
        while current:
            print(current.data)
            current = current.next

ll = LinkedList()
ll.append(1)
ll.append(2)
ll.append(3)
ll.append(4)
print("Original List:")
ll.print_list()
ll.reverse()
print("Reversed List:")
ll.print_list()




Original List:
1
2
3
4
Reversed List:
4
3
2
1


In [ ]:
#46.Python Program for Find largest prime factor of a number

import math

# A function to find largest prime factor
def maxPrimeFactors (n):

	maxPrime = -1
	
	while n % 2 == 0:
		maxPrime = 2
		n >>= 1	 # equivalent to n /= 2
		
	
	for i in range(3, int(math.sqrt(n)) + 1, 2):
		while n % i == 0:
			maxPrime = i
			n = n / i
	
	
	if n > 2:
		maxPrime = n
	
	return int(maxPrime)

n = 15
print(maxPrimeFactors(n))

n = 25698751364526
print(maxPrimeFactors(n))


5
328513


In [ ]:
#47.Python Program for Efficient program to print all prime factors of a given number

import math
# prime
def primeFactors(n):
   # no of even divisibility
   while n % 2 == 0:
      print (2),
      n = n / 2
   # n reduces to become odd
   for i in range(3,int(math.sqrt(n))+1,2):
      # while i divides n
      while n % i== 0:
         print (i)
         n = n / i
   # if n is a prime
   if n > 2:
      print (n)
n = 200
primeFactors(n)

2
2
2
5
5


In [ ]:
#48.Python Program for Product of unique prime factors of a number

def productPrimeFactors(n):
	product = 1
	
	for i in range(2, n+1):
		if (n % i == 0):
			isPrime = 1
			
			for j in range(2, int(i/2 + 1)):
				if (i % j == 0):
					isPrime = 0
					break
				
			if (isPrime):
				product = product * i
				
	return product
	

n = 44
print (productPrimeFactors(n))

22


In [ ]:
#49.Python Program for Find sum of odd factors of a number

# Give the number as static input and store it in a variable.
gvn_numb = 24
# Take an empty list and store it in another variable.
all_factors = []
# Loop from '1' to above given number range using For loop.
for itr in range(1, gvn_numb+1):
    # Check whether the given number modulus iterator value is equal to '0' or not
    # using if conditional statement.
    if gvn_numb % itr == 0:
        # If the statement is True, Check if the iterator modulus 2 is not equal to 0 using the
        # if conditional statement.
        if itr % 2 != 0:
            # If the statement is True ,append the iterator value to the above declared list .
            all_factors.append(itr)
      # Get the sum of all the odd factors of above got list using built-in sum() function
      # and store it in another variable.
reslt = sum(all_factors)
# Print the sum of all odd factors of a given number.
print("The Sum of all odd factors of {", gvn_numb, "}  = ", reslt)

The Sum of all odd factors of { 24 }  =  4


In [ ]:
#50.Python Program for Coin Change

def count(S, m, n):
    # If n is 0 then there is 1 solution (do not include any coin)
    if n == 0:
        return 1
    # If n is less than 0 then no solution exists
    if n < 0:
        return 0
    # If there are no coins and n is greater than 0, then no solution exist
    if m <=0 and n >= 1:
        return 0
    # count is sum of solutions (i) including S[m-1] (ii) excluding S[m-1]
    return count( S, m - 1, n ) + count( S, m, n-S[m-1] );

# Driver program to test above function
arr = [1, 2, 3]
m = len(arr)
n = 4
x = count(arr, m, n)
print (x)


4
